# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(editable=False, max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[(b'active', 'Active'), (b'ignored', 'Ignored'), (b'inactive', 'Inactive')], default=b'active', help_text='Depending on its value, determine whether it could alter the bank account balance or being used by statistics.', max_length=32, verbose_name='Status')),
                ('reconciled', models.BooleanField(default=False, help_text='Whether the bank transaction has been applied on the real bank account.', verbose_name='Reconciled')),
                ('payment_method', models.CharField(choices=[(b'credit_card', 'Credit card'), (b'cash', 'Cash'), (b'transfer', 'Transfer'), (b'transfer_internal', 'Transfer internal'), (b'check', 'Check')], default=b'credit_card', max_length=32, verbose_name='Payment method')),
                ('memo', models.TextField(blank=True, verbose_name='Memo')),
                ('scheduled', models.BooleanField(default=False, editable=False)),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banktransactions', to='bankaccounts.BankAccount')),
            ],
            options={
                'db_table': 'banktransactions',
                'get_latest_by': 'date',
            },
        ),
    ]
