# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_ui', models.BooleanField(default=False)),
                ('start_page', models.CharField(choices=[(b'Project Details', b'Project Details'), (b'Tasks', b'Tasks'), (b'Todos', b'Todos'), (b'Wiki', b'Wiki'), (b'Metrics', b'Metrics'), (b'Logs', b'Logs')], max_length=100)),
                ('user', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
