# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[(b'Submitted', 'Submitted'), (b'Confirmed', 'Confirmed'), (b'Rejected', 'Rejected')], default=b'Submitted', max_length=20, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractInvestmentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default=b'', max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from=b'name', unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('users', models.ManyToManyField(blank=True, related_name='investors', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'ordering': ('name', 'code'),
                'abstract': False,
                'verbose_name': 'Fulfillment investor',
                'verbose_name_plural': 'Fulfillment investors',
                'permissions': (('dashboard_access', 'Can access dashboard'),),
            },
        ),
        migrations.CreateModel(
            name='InvestorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[(b'Mr', 'Mr'), (b'Miss', 'Miss'), (b'Mrs', 'Mrs'), (b'Ms', 'Ms'), (b'Dr', 'Dr')], max_length=64, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('line3', models.CharField(blank=True, max_length=255, verbose_name='Third line of address')),
                ('line4', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', oscar.models.fields.UppercaseCharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='investor.Investor', verbose_name='Investor')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Investor address',
                'verbose_name_plural': 'Investor addresses',
            },
        ),
        migrations.CreateModel(
            name='ProjectAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Title')),
                ('proposal', models.CharField(choices=[(b'\xe5\x88\x9b\xe5\xbb\xba\xe5\x90\x88\xe8\xb5\x84\xe5\x85\xac\xe5\x8f\xb8', 'Joint Venture'), (b'\xe9\xa1\xb9\xe7\x9b\xae\xe6\x8b\x9b\xe6\xa0\x87', 'Project tender')], default=b'\xe5\x88\x9b\xe5\xbb\xba\xe5\x90\x88\xe8\xb5\x84\xe5\x85\xac\xe5\x8f\xb8', max_length=20, verbose_name='Proposal')),
                ('scale_of_funding', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Scale of funding')),
                ('share_ratio', models.CharField(choices=[(b'25%', '25%'), (b'50%', '50%'), (b'75%', '75%'), (b'100%', '100%')], default=b'100%', max_length=20, verbose_name='Share ratio')),
                ('proposal_details', models.TextField(blank=True, verbose_name='Proposal details')),
                ('status', models.CharField(choices=[(b'Active', 'Active'), (b'Cancelled', 'Cancelled'), (b'Closed', 'Closed')], default=b'Active', max_length=20, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectannouncement', to='investor.Investor', verbose_name='Investor')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Investor Project Announcement',
                'verbose_name_plural': 'Investor Project Announcement',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('abstractinvestment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investor.AbstractInvestment')),
            ],
            bases=('investor.abstractinvestment',),
        ),
        migrations.CreateModel(
            name='InvestmentComment',
            fields=[
                ('abstractinvestmentcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investor.AbstractInvestmentComment')),
            ],
            bases=('investor.abstractinvestmentcomment',),
        ),
        migrations.AddField(
            model_name='abstractinvestmentcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='abstractinvestment',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investor.Investor', verbose_name='Investor'),
        ),
        migrations.AddField(
            model_name='abstractinvestment',
            name='prospectus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProspectus'),
        ),
        migrations.AddField(
            model_name='abstractinvestment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='abstractinvestmentcomment',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Investment', to='investor.Investment', verbose_name='Investment'),
        ),
    ]
