# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from=b'name', unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
            ],
            options={
                'ordering': ('name', 'code'),
                'abstract': False,
                'verbose_name': 'Fulfillment company',
                'verbose_name_plural': 'Fulfillment companys',
                'permissions': (('dashboard_access', 'Can access dashboard'),),
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[(b'Mr', 'Mr'), (b'Miss', 'Miss'), (b'Mrs', 'Mrs'), (b'Ms', 'Ms'), (b'Dr', 'Dr')], max_length=64, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('line3', models.CharField(blank=True, max_length=255, verbose_name='Third line of address')),
                ('line4', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', oscar.models.fields.UppercaseCharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company.Company', verbose_name='Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Company address',
                'verbose_name_plural': 'Company addresses',
            },
        ),
        migrations.CreateModel(
            name='CompanyProspectus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Title')),
                ('fundraising_sclae', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fund raising sclae')),
                ('total_share_capital', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total share capital')),
                ('proposal_details', models.TextField(blank=True, verbose_name='Proposal details')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=b'companys', verbose_name='Image')),
                ('status', models.CharField(choices=[(b'Unconfirmed', 'Not yet confirmed'), (b'Active', 'Active'), (b'Cancelled', 'Cancelled'), (b'Closed', 'Closed')], default=b'Active', max_length=20, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectus', to='company.Company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Company prospectus',
                'verbose_name_plural': 'Company prospectus',
            },
        ),
    ]
