# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='company_set', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
