# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(editable=False, max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[(b'active', 'Active'), (b'ignored', 'Ignored'), (b'inactive', 'Inactive')], default=b'active', help_text='Depending on its value, determine whether it could alter the bank account balance or being used by statistics.', max_length=32, verbose_name='Status')),
                ('reconciled', models.BooleanField(default=False, help_text='Whether the bank transaction has been applied on the real bank account.', verbose_name='Reconciled')),
                ('payment_method', models.CharField(choices=[(b'credit_card', 'Credit card'), (b'cash', 'Cash'), (b'transfer', 'Transfer'), (b'transfer_internal', 'Transfer internal'), (b'check', 'Check')], default=b'credit_card', max_length=32, verbose_name='Payment method')),
                ('memo', models.TextField(blank=True, verbose_name='Memo')),
                ('type', models.CharField(choices=[(b'monthly', 'Monthly'), (b'weekly', 'Weekly')], default=b'monthly', help_text='The type of recurrence to be applied.', max_length=32, verbose_name='Type')),
                ('recurrence', models.PositiveSmallIntegerField(blank=True, help_text='How many time the bank transaction should be cloned.', null=True, verbose_name='Recurrence')),
                ('last_action', models.DateTimeField(editable=False, help_text='Last time the scheduled bank transaction has been cloned.', null=True)),
                ('state', models.CharField(choices=[(b'waiting', 'Waiting'), (b'finished', 'Finished'), (b'failed', 'Failed')], default=b'waiting', editable=False, help_text='State of the scheduled bank transaction.', max_length=32)),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banktransactionschedulers', to='bankaccounts.BankAccount')),
            ],
            options={
                'db_table': 'banktransactionschedulers',
            },
        ),
    ]
