# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banktransactiontags', '0001_initial'),
        ('banktransactionschedulers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionscheduler',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banktransactionschedulers', to='banktransactiontags.BankTransactionTag', verbose_name='Tag'),
        ),
        migrations.AlterIndexTogether(
            name='banktransactionscheduler',
            index_together=set([('state', 'last_action')]),
        ),
    ]
